AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bucketquery

  Sample SAM Template for bucketquery

Parameters:
    CovidDataBucketName:
        Type: String
    CovidDataProvinceFileName:
        Type: String
    CovidDataRegionFileName:
        Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CovidDataApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      OpenApiVersion: 3.0.3
      Name: CovidDataApi
      StageName: Prod
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 40
          ThrottlingRateLimit: 30

  CovidDataProvQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: coviddata/
      Handler: app_prov.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
            BUCKET_NAME: !Ref CovidDataBucketName
            PROV_FILE_NAME: !Ref CovidDataProvinceFileName
      Policies: 
        - S3ReadPolicy:
            BucketName: !Ref CovidDataBucketName
      Events:
        CovidData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /covid-data/prov
            Method: get
            RestApiId: !Ref CovidDataApi

    
  CovidDataRegionQueryFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: coviddata/
      Handler: app_region.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
            BUCKET_NAME: !Ref CovidDataBucketName
            REGION_FILE_NAME: !Ref CovidDataRegionFileName
      Policies: 
        - S3ReadPolicy:
            BucketName: !Ref CovidDataBucketName
      Events:
        CovidData:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /covid-data/region
            Method: get
            RestApiId: !Ref CovidDataApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CovidDataApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${CovidDataApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/covid-data/"
  CovidDataProvQueryFunction:
    Description: "Covid Data Province Lambda Function ARN"
    Value: !GetAtt CovidDataProvQueryFunction.Arn
  CovidDataRegionQueryFunction:
    Description: "Covid Data Region Lambda Function ARN"
    Value: !GetAtt CovidDataRegionQueryFunction.Arn
  CovidDataLatestIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CovidDataProvQueryFunction.Arn
